# Generated by Django 4.2.6 on 2023-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_active_productline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
